export const HOME_API_CALL = 'HOME_API_CALL';
export const HOME_API_CALL_SUCCESS = 'HOME_API_CALL_SUCCESS';
export const HOME_API_CALL_FAILURE = 'HOME_API_CALL_FAILURE';
export const HOME_LOADER = 'HOME_LOADER';

// export const LOGIN_API_CALL = 'LOGIN_API_CALL';
// export const LOGIN_API_CALL_SUCCESS = 'LOGIN_API_CALL_SUCCESS';
// export const LOGIN_API_CALL_FAILURE = 'LOGIN_API_CALL_FAILURE';
// export const LOGIN_LOADER = 'LOGIN_LOADER';
